# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973a026288c3f190ba7c79c0ad060a2e339c404f116e9dfc96a9cb729ece0438900a460181377568e56d859915723b0ad957ebed3e9be56a648690937ecc804b

test:
  secret_key_base: 445983434e4778cef2c5c214750589280dd1d7f8f2c46910a02446a789d984491b7aaa19cb214f71790da4bea96db89f22f57cc501277db6077ae794cd74cd05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
